apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ticket-service.fullname" . }}-config
  labels:
    {{- include "ticket-service.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
