# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test & Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        module:
          - apps/business-partners-service
          # - apps/employee-service
          # - apps/notification-service
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build commons/generic-data
        working-directory: commons/generic-data
        run: mvn -B clean install

      - name: Build module
        working-directory: ${{ matrix.module }}
        run: mvn -B clean compile

    outputs:
      module: ${{ matrix.module }}

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - apps/business-partners-service
          - apps/employee-service
          - apps/notification-service

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build commons/generic-data
        working-directory: commons/generic-data
        run: mvn -B clean install

      - name: Run tests
        working-directory: ${{ matrix.module }}
        run: mvn -B test
